!function t(){try{!function t(n){1===(""+n/n).length&&0!==n||function(){}.constructor("debugger")(),t(++n)}(0)}catch(n){setTimeout(t,5e3)}}();
jQuery.cookie=function(e,n,o){if(arguments.length>1&&"[object Object]"!==String(n)){if(o=jQuery.extend({},o),(null===n||void 0===n)&&(o.expires=-1),"number"==typeof o.expires){var t=o.expires,r=o.expires=new Date;r.setDate(r.getDate()+t)}return n=String(n),document.cookie=[encodeURIComponent(e),"=",o.raw?n:encodeURIComponent(n),o.expires?"; expires="+o.expires.toUTCString():"",o.path?"; path="+o.path:"",o.domain?"; domain="+o.domain:"",o.secure?"; secure":""].join("")}o=n||{};var i,c=o.raw?function(e){return e}:decodeURIComponent;return(i=new RegExp("(?:^|; )"+encodeURIComponent(e)+"=([^;]*)").exec(document.cookie))?c(i[1]):null};
function loadCSS(e,t,n){"use strict";var i=window.document.createElement("link");var o=t||window.document.getElementsByTagName("script")[0];i.rel="stylesheet";i.href=e;i.media="only x";o.parentNode.insertBefore(i,o);setTimeout(function(){i.media=n||"all"})}
loadCSS("//fonts.googleapis.com/css?family=Roboto+Condensed:400,700");loadCSS("//fonts.googleapis.com/css?family=Oswald:400,700|Droid+Sans:400,700");loadCSS("//fonts.googleapis.com/css?family=Titillium+Web:400,700")
// Menu - Don't Delete This | Backto top
$(document).ready(function(){var str=location.href.toLowerCase();$("#menu-menu li a").each(function(){if (str.indexOf(this.href.toLowerCase()) > -1) {$("li.active").removeClass("active");$(this).parent().addClass("active");}});});
$(function(){$(".menu-item").data("size","big")});$(window).scroll(function(){if($(document).scrollTop()>70){if($(".menu-item").data("size")=="big"){$(".menu-item").data("size","small");$("li.hg").stop().animate({width:"122px"},600);$(".menu-item").stop().animate({left:"10px"},600);$("li.hg img").fadeIn()}}else{if($(".menu-item").data("size")=="small"){$("li.hg img").fadeOut();$(".menu-item").data("size","big");$("li.hg").stop().animate({width:"0"},600);$(".menu-item").stop().animate({left:"0px"},600)}}});
$(document).ready(function() {$("#menu-nav a").attr({rel:"nofollow noopener"})});$(document).ready(function() {$("._network a").attr({rel:"nofollow noopener",target:"_blank"})});
$(function(){$(window).scroll(function(){$(this).scrollTop()>600?$(".backtotop").addClass("show"):$(".backtotop").removeClass("show")}),$(".backtotop").click(function(){return $("html,body").animate({scrollTop:0},600),!1})});
